steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "Dockerfile.collector", "-t", "${_IMAGE}", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]
images: ["${_IMAGE}"]
timeout: "1800s"
substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/example/instatrack/collector:latest
