steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${COMMIT_SHA}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${COMMIT_SHA}
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.collector
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/collector:${COMMIT_SHA}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/collector:${COMMIT_SHA}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${COMMIT_SHA}
      - --region=${_REGION}
      - --project=${PROJECT_ID}
      - --quiet
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - ${_SERVICE_NAME}-collector
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/collector:${COMMIT_SHA}
      - --region=${_REGION}
      - --project=${PROJECT_ID}
      - --quiet
substitutions:
  _REGION: europe-west1
  _REPOSITORY: instatrack
  _SERVICE_NAME: instatrack-crm
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s
