import type { CollectionRun, DashboardData, Profile, Reel } from "./api";
const ago=(days:number)=>new Date(Date.now()-days*86400000).toISOString();
export const demoProfiles:Profile[]=[
{id:"p1",username:"citystories",instagram_url:"https://instagram.com/citystories/",display_name:"City Stories",biography:"Small stories from beautiful cities.",profile_picture_url:null,followers_count:184200,followers_state:"available",followers_observed_at:ago(0),added_by:"Saba",is_active:true,last_collected_at:ago(0),last_error:null,created_at:ago(25)},
{id:"p2",username:"tastegeorgia",instagram_url:"https://instagram.com/tastegeorgia/",display_name:"Taste Georgia",biography:"Georgian food, people and places.",profile_picture_url:null,followers_count:94100,followers_state:"available",followers_observed_at:ago(0),added_by:"Dachi",is_active:true,last_collected_at:ago(0),last_error:null,created_at:ago(18)},
{id:"p3",username:"weekendroutes",instagram_url:"https://instagram.com/weekendroutes/",display_name:"Weekend Routes",biography:"Routes worth taking.",profile_picture_url:null,followers_count:71600,followers_state:"stale",followers_observed_at:ago(2),added_by:"Lui",is_active:true,last_collected_at:ago(2),last_error:"Instagram temporarily limited anonymous access",created_at:ago(12)},
{id:"p4",username:"studio_daily",instagram_url:"https://instagram.com/studio_daily/",display_name:"Studio Daily",biography:null,profile_picture_url:null,followers_count:null,followers_state:"unavailable",followers_observed_at:null,added_by:"Saba",is_active:true,last_collected_at:null,last_error:null,created_at:ago(1)}];
export const demoReels:Reel[]=[
{id:"r1",profile_id:"p1",shortcode:"demo1",permalink:"https://instagram.com/reel/demo1/",caption:"A quiet morning in Tbilisi #tbilisi #citylife",hashtags:["tbilisi","citylife"],thumbnail_url:null,published_at:ago(1),views_count:184000,likes_count:8200,comments_count:312,metrics_state:"available",metrics_observed_at:ago(0),views_source:"video_view_count",engagement_rate:4.62,profile_username:"citystories"},
{id:"r2",profile_id:"p2",shortcode:"demo2",permalink:"https://instagram.com/reel/demo2/",caption:"Khinkali in 30 seconds #georgianfood",hashtags:["georgianfood"],thumbnail_url:null,published_at:ago(3),views_count:97000,likes_count:4900,comments_count:174,metrics_state:"available",metrics_observed_at:ago(0),views_source:"video_view_count",engagement_rate:5.39,profile_username:"tastegeorgia"},
{id:"r3",profile_id:"p3",shortcode:"demo3",permalink:"https://instagram.com/reel/demo3/",caption:"The road to Kazbegi #kazbegi #georgia",hashtags:["kazbegi","georgia"],thumbnail_url:null,published_at:ago(5),views_count:61000,likes_count:2700,comments_count:89,metrics_state:"stale",metrics_observed_at:ago(2),views_source:"video_view_count",engagement_rate:3.9,profile_username:"weekendroutes"},
{id:"r4",profile_id:"p4",shortcode:"demo4",permalink:"https://instagram.com/reel/demo4/",caption:"Behind the latest campaign #studio",hashtags:["studio"],thumbnail_url:null,published_at:ago(6),views_count:null,likes_count:null,comments_count:null,metrics_state:"unavailable",metrics_observed_at:null,views_source:null,engagement_rate:null,profile_username:"studio_daily"}];
const series=[41,59,53,76,68,94,108,97,126,143,132,168].map((v,i)=>({observed_at:ago(22-i*2),views:v*1000}));const total=(field:"views_count"|"likes_count"|"comments_count")=>demoReels.reduce((sum,reel)=>sum+(reel[field]||0),0);
export const demoDashboard:DashboardData={views:{value:total("views_count"),previous_value:286000,change_percent:19.6,observed_at:ago(0),state:"available"},likes:{value:total("likes_count"),previous_value:null,change_percent:18,observed_at:ago(0),state:"available"},comments:{value:total("comments_count"),previous_value:null,change_percent:12.4,observed_at:ago(0),state:"available"},followers:{value:demoProfiles.reduce((s,p)=>s+(p.followers_count||0),0),previous_value:null,change_percent:2.6,observed_at:ago(0),state:"available"},views_series:series,top_reels:demoReels.slice(0,3),recent_reels:demoReels};
export const demoRuns:CollectionRun[]=[{id:"c1",status:"partial",trigger:"scheduled",started_at:ago(0),completed_at:ago(0),profiles_total:4,profiles_succeeded:3,profiles_failed:1,error:null},{id:"c2",status:"succeeded",trigger:"scheduled",started_at:ago(1),completed_at:ago(1),profiles_total:3,profiles_succeeded:3,profiles_failed:0,error:null}];
